### ISSUE TITLE
Unable to reproduce README instructions

### ISSUE THREAD

**Issue by breandan** [JetBrains-Research/ast-transformations#45]
One of your colleagues [suggested](https://github.com/JetBrains-Research/astminer/discussions/195#discussioncomment-1611089) using this project. It looks very nice! When I tried to use it, I was unable to reproduce your README instructions, either as a tool or a library. When I ran the tool command from the parent directory,

`./gradlew :cli -Pinput=../gym-fs/src/main/resources/datasets/python/ -Poutput=../gym-fs/src/main/resources/datasets/ -Pyaml=config.yaml`

this produced the following output:

```
Downloading https://services.gradle.org/distributions/gradle-6.8.3-bin.zip
..........10%..........20%..........30%...........40%..........50%..........60%..........70%...........80%..........90%..........100%

Welcome to Gradle 6.8.3!

Here are the highlights of this release:
 - Faster Kotlin DSL script compilation
 - Vendor selection for Java toolchains
 - Convenient execution of tasks in composite builds
 - Consistent dependency resolution

For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'cli' not found in root project 'ast-transformations'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
```

I also tried to use it inside another project using the library instructions, but this produced an empty JAR file:

![Screen Shot 2021-11-24 at 2 20 34 AM](https://user-images.githubusercontent.com/175716/143192869-2ed605fe-81bb-446e-b0f9-856d75393893.png)

**Comment by nbirillo** [comment]
@breandan Oh, sorry, I haven't seen this issue since you did not mentioned me. Is it valuable for you now? I will check the plugin today and will publish an update if it is necessary

**Comment by nbirillo** [comment]
I fixed it
